version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.65.0

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Run Tests
          command: "cargo test"

workflows:
  test:
    jobs:
      - test
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_ECR_REPO_NAME}"
          region: "${AWS_REGION}"
          tag: "latest,${CIRCLE_SHA1}"
